# Generated by Django 4.2.7 on 2023-11-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_portfolioworkimage_src'),
        ('market', '0002_workorderemployerreview_workorderemployeereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='workorderrequest',
            name='payment_type',
            field=models.CharField(choices=[(0, 'Full Payment'), (1, 'Step Payment')], default=0, max_length=50, verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[(0, 'Waiting'), (1, 'Active'), (2, 'Canceled')], default=0, max_length=60, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ActiveWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=70, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('term', models.PositiveIntegerField(verbose_name='Term')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('status', models.CharField(choices=[(0, 'Active'), (0, 'Checking'), (0, 'Approved'), (4, 'Aborted')], default=0, max_length=60, verbose_name='Status')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_work_orders', to='users.employeeprofile', verbose_name='Employee')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_work_orders', to='users.employerprofile', verbose_name='Employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='workorderemployeereview',
            name='work_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_review', to='market.activeworkorder', verbose_name='Work Order'),
        ),
        migrations.AlterField(
            model_name='workorderemployerreview',
            name='work_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_review', to='market.activeworkorder', verbose_name='Work Order'),
        ),
        migrations.AlterField(
            model_name='workorderpaymentstep',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_steps', to='market.activeworkorder', verbose_name='Work Order'),
        ),
        migrations.AlterField(
            model_name='workorderservice',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='market.activeworkorder', verbose_name='Work Order'),
        ),
    ]
