# Generated by Django 4.2.7 on 2023-11-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_portfolioworkimage_src'),
        ('market', '0003_remove_workorder_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderRequestPaymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(max_length=100, verbose_name='Title')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('work_order_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_steps', to='market.workorderrequest', verbose_name='Work Order Request')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='WorkOrderPaymentStep',
            new_name='ActiveWorkOrderPaymentStep',
        ),
        migrations.RemoveField(
            model_name='activeworkorder',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activeworkorder',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='activeworkorder',
            name='title',
        ),
        migrations.AddField(
            model_name='activeworkorder',
            name='work_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_work_order', to='market.workorder', verbose_name='Work Order'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_work_orders', to='users.employeeprofile', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[(0, 'Waiting'), (1, 'Active'), (2, 'Canceled'), (3, 'Declined')], default=0, max_length=60, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='EmployeeFavouriteWorkOrder',
        ),
    ]
