# Generated by Django 4.2.7 on 2023-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_workorderrequestpaymentstep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeworkorderpaymentstep',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='Summary'),
        ),
    ]
