# Generated by Django 4.2.7 on 2023-11-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_activeworkorderpaymentstep_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeworkorderpaymentstep',
            name='summary',
            field=models.TextField(verbose_name='Summary'),
        ),
    ]
