# Generated by Django 4.2.7 on 2023-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioworkimage',
            name='src',
            field=models.ImageField(upload_to='media/users/portfolio_works/', verbose_name='Source'),
        ),
    ]
