# Generated by Django 4.2.7 on 2023-11-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_workorderrequestpaymentstep_and_more'),
        ('users', '0011_alter_portfolioworkimage_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='employeeportfoliowork',
            name='work_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_portfolio_work', to='market.workorder', verbose_name='Work Order'),
        ),
        migrations.CreateModel(
            name='EmployeeFavouriteWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_work_orders', to='users.employeeprofile', verbose_name='Employee')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_employees', to='market.workorder', verbose_name='Work Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
